In [75]:
import pandas as pd
import numpy as np

#dataframe e a tabela estrutura dentro do frame, base de dados do panda (df) // forma de carregar e visualizar
df_vendas = pd.read_csv("vendas_tech.csv", low_memory=False)
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")
display(df_vendas)
display(df_gerentes)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [76]:
#inspecao
display(df_vendas)
#display(df_vendas.head(15)) #primeiras
#display(df_vendas.tail(15)) #ultimas
#display(df_vendas.sample(15)) #aleatorio
display(df_vendas.shape) #tamanho da tabela
display(df_vendas.columns) #colunas
display(list(df_vendas.columns)) #colunas, transformando em lista PY
display(df_vendas.info()) #pegar informaçoes, e verificar erros
display(df_vendas.describe()) #descrever a base de dados, descricao estatistica, numericos, medicas, valor miniomo, maximo, quartos

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

(100100, 8)

Index(['ID_Pedido', 'Data', 'Loja', 'Produto', 'Preco_Unitario', 'Qtd',
       'Cliente', 'Data_Base'],
      dtype='str')

['ID_Pedido',
 'Data',
 'Loja',
 'Produto',
 'Preco_Unitario',
 'Qtd',
 'Cliente',
 'Data_Base']

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

In [77]:
#tratamendo de dados
#display(df_vendas["Loja"]) #acessar coluna, seleçao de coluna
#display(df_vendas[["Loja", "Cliente"]]) #acessar mais colunas, colocar dois couchetes ou setar antes numa variavel as colunas que quiser

#trabalhar com colunas
df_vendasv2 = df_vendas.drop(columns=["Data_Base"])#excluir uma coluna, duas tres, varias (criando a v2 para nao mexer na original)

#tratar valores nulos
#df_vendasv2 = df_vendasv2.dropna() #comando mais simples, exlui todas as linhas que tem 1 valor vazio
df_vendasv2["Loja"] = df_vendasv2["Loja"].fillna("Online") #editando apenas coluna loja, porem poderia colocar tudo em uma linha

#tipos de dados
df_vendasv2["Data"] = pd.to_datetime(df_vendasv2["Data"], format="%Y-%m-%d") #transforma o tipo da coluna para data do py **pesquisar tabela para usar o formato correto

#padronizaçao
df_vendasv2["Loja"] = df_vendasv2["Loja"].str.strip() #remove espaço duplicado, espaço vazio no inicio ou final do texto
df_vendasv2["Loja"] = df_vendasv2["Loja"].str.title() #padronizar o nome das lojas com a primeira letra maiuscula resto minusculo

df_gerentes["Loja"] = df_gerentes["Loja"].str.strip() #remove espaço duplicado, espaço vazio no inicio ou final do texto
df_gerentes["Loja"] = df_gerentes["Loja"].str.title() #padronizar o nome das lojas com a primeira letra maiuscula resto minusculo

#duplicatas
df_vendasv2 = df_vendasv2.drop_duplicates(subset=["ID_Pedido"], keep="first")#remove duplicadas, mantem o primeiro valor

display(df_vendasv2)
display(df_vendasv2.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 5.3 MB

None

In [78]:
# criando novas colunas
#faturamento
df_vendasv2["Faturamento"] = df_vendasv2["Qtd"] * df_vendasv2["Preco_Unitario"] #adicionando uma nova coluna de Faturamento entre valor do produto e a quantidade

#forma de venda
df_vendasv2["Forma_de_Venda"] = np.where(df_vendasv2["Loja"] == "Online", "Online", "Presencial") #aplicando condicional como se fosse if, else, para adicionar a colona Forma de venda entre online e presencial

#regiao------------
display(df_vendasv2["Loja"].unique()) #usando funçao, coluna especifica ex(unique, mean,sum,count,value_counts)
#opcao1
#df_vendasv2["Regiao"] = np.where(df_vendasv2["Loja"]== "Porto alegre", "Sul")...
#opcao2
#sul = ["Curitiba", "Porto Alegre"]
#df_vendasv2["Regiao"] = np.where(df_vendasv2["Loja"].isin(sul), "Sul")
#opcao3
# def definir_regiao(loja): #criando uma funcao metodo complexo
#     dic_regioes = {
#     'São Paulo' : "Sudeste",
#     'Belo Horizonte' : "Sudeste",
#     'Online' : "Online",
#     'Rio De Janeiro' : "Sudeste",
#     'Salvador' : "Nordeste",
#     'Recife' : "Nordeste",
#     'Curitiba' : "Sul",
#     'Porto Alegre' : "Sul"
# }
#     return dic_regioes[loja]

#opcao4 - apenas com o dicionario ja basta
dic_regioes = {
    'São Paulo' : "Sudeste",
    'Belo Horizonte' : "Sudeste",
    'Online' : "Online",
    'Rio De Janeiro' : "Sudeste",
    'Salvador' : "Nordeste",
    'Recife' : "Nordeste",
    'Curitiba' : "Sul",
    'Porto Alegre' : "Sul"
}

df_vendasv2["Regiao"] = df_vendasv2["Loja"].map(dic_regioes)

display(df_vendasv2)
#display(df_vendasv2.info())
display(df_vendasv2.isna().sum()) #aplicando funcao na base inteira. em todas colunas, verificando se esta vazio e somar para verificar

<StringArray>
[     'São Paulo', 'Belo Horizonte',         'Online', 'Rio De Janeiro',
       'Salvador',         'Recife',       'Curitiba',   'Porto Alegre']
Length: 8, dtype: str

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial,Sudeste
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial,Sul
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial,Sul
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Presencial,Sul

ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
Faturamento       0
Forma_de_Venda    0
Regiao            0
dtype: int64

In [79]:
#analisar - filtrar

#ordenar a base por coluna
df_vendasv2 = df_vendasv2.sort_values(by=["Data", "Faturamento"]) ##se quiser mudar a ordem do maior pro menor anscendig=
df_vendasv2 = df_vendasv2.reset_index(drop=True) #reset no index para deixar os indices do 0 ao ultimo, e deletar o indice antigo, para nao criar outra coluna


#localizar algo especifico em uma linha e uma coloca # .loc: id do pedido - - pelo nome da coluna e do indice
id_pedido = 4
loja = df_vendasv2.loc[df_vendasv2["ID_Pedido"] == 4, "Loja"].values[0]
produto = df_vendasv2.loc[df_vendasv2["ID_Pedido"] == 4, "Produto"].values[0]
cliente = df_vendasv2.loc[df_vendasv2["ID_Pedido"] == 4, "Cliente"].values[0]
print(loja)
print(produto)
print(cliente)

#por posicao -> .iloc
id_pedido = 4
loja = df_vendasv2.iloc[3,2]
produto = df_vendasv2.iloc[3,3]
cliente = df_vendasv2.iloc[3,6]
print(loja, produto, cliente)


#condicional - linha toda da tabela separada
#df_id_pedido_4 = df_vendasv2[df_vendasv2["ID_Pedido"] == 4]

#exportar pedaços da base
#vendas de sp
df_vendas_sp = df_vendasv2[df_vendasv2["Loja"] == "São Paulo"]
#exportar pro chefe, mandar para alguem
df_vendas_sp.to_csv("Vendas_SP.csv", index=False)

#exportar vendas de 2024
df_vendas_2024 = df_vendasv2[df_vendasv2["Data"].dt.year == 2024]
df_vendas_2024.to_csv("Vendas_2024.csv", index=False)

#duplas condicoes
df_vendas_HDMI_SUL = df_vendasv2[(df_vendasv2["Produto"] == "Cabo HDMI") & (df_vendasv2["Regiao"] == "Sul")]

display(df_vendas_HDMI_SUL)

Rio De Janeiro
Mouse Gamer
Cliente_17343
Porto Alegre Cabo HDMI Cliente_22886

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
0,1700,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_14435,40.0,Presencial,Sul
2,35599,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_18680,40.0,Presencial,Sul
3,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,40.0,Presencial,Sul
4,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,40.0,Presencial,Sul
9,70138,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_9348,40.0,Presencial,Sul
...,...,...,...,...,...,...,...,...,...,...
99874,75695,2024-12-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_29587,40.0,Presencial,Sul
99875,78584,2024-12-30,Curitiba,Cabo HDMI,40.0,1,Cliente_21307,40.0,Presencial,Sul
99880,35127,2024-12-30,Curitiba,Cabo HDMI,40.0,2,Cliente_20687,80.0,Presencial,Sul
99881,47774,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_14363,80.0,Presencial,Sul
99882,64473,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_11598,80.0,Presencial,Sul

In [80]:
#analises por agrupamento
#display(df_vendasv2)
#qual loja vendeu mais?
analise_lojas = df_vendasv2[["Loja", "Faturamento"]].groupby("Loja").sum() ##pegando o faturamento de cada loja e somando cada faturamento
analise_lojas = analise_lojas.sort_values(by="Faturamento", ascending=False) #ordenando do maior para o menor
analise_lojas = analise_lojas.reset_index()
analise_lojas["Faturamento"] = analise_lojas["Faturamento"].map("R${:,.2f}".format) ##formatando para real
display(analise_lojas)

#ranking de produtos que mais venderam no online
df_vendas_online = df_vendasv2[df_vendasv2["Loja"] == "Online"]
analise_produtos_online = df_vendas_online[["Produto", "Qtd"]].groupby("Produto").sum() ##pegando a quantidade de cada produto e somando qual vendeu mais
df_produtos_online = analise_produtos_online.sort_values(by="Qtd", ascending=False) #ordenando do maior para o menor
analise_produtos_online = analise_produtos_online.rename(columns={"Qtd":"Vendas Totais"}) #trocar o nome da coluna de uma tabela
display(analise_produtos_online)

#analise de ranking por loja e por produto
#quais produtos venderam mais em cada uma das lojas
analise_produtos_em_lojas = df_vendasv2[["Loja", "Produto", "Qtd"]].groupby(["Loja", "Produto"]). sum() ##pegando a quantidade de cada loja e produto e somando qual vendeu mais

#quais lojas mais venderam os produtos
analise_lojas_em_produtos = df_vendasv2[["Loja", "Produto", "Qtd"]].groupby(["Produto", "Loja"]). sum() ##pegando a quantidade de cada produto e loja e somando qual vendeu mais


##somente para este display fazer aparecer todos os dados da tabela
with pd.option_context("display.max_rows", None):
    display(analise_produtos_em_lojas)
    display(analise_lojas_em_produtos)

             Loja      Faturamento
0        Salvador  R$42,300,610.00
1  Rio De Janeiro  R$42,294,720.00
2          Recife  R$42,190,390.00
3       São Paulo  R$42,090,690.00
4  Belo Horizonte  R$41,714,890.00
5    Porto Alegre  R$41,678,460.00
6        Curitiba  R$41,121,720.00
7          Online   R$6,080,850.00

                    Vendas Totais
Produto
Cabo HDMI                     403
Monitor 27"                   332
Mouse Gamer                   379
Notebook Dell                 369
Notebook HP                   442
Smartphone Samsung            311
Teclado Mecânico              343
iPhone 14                     390

                                    Qtd
Loja           Produto
Belo Horizonte Cabo HDMI           2636
               Monitor 27"         2625
               Mouse Gamer         2465
               Notebook Dell       2654
               Notebook HP         2775
               Smartphone Samsung  2597
               Teclado Mecânico    2609
               iPhone 14           2478
Curitiba       Cabo HDMI           2698
               Monitor 27"         2626
               Mouse Gamer         2600
               Notebook Dell       2517
               Notebook HP         2529
               Smartphone Samsung  2444
               Teclado Mecânico    2742
               iPhone 14           2652
Online         Cabo HDMI            403
               Monitor 27"          332
               Mouse Gamer          379
               Notebook Dell        369
               Notebook HP          442
               Smartphone Samsung   311
               Teclado Mecânico     343
               iPhone 14            390
Porto Alegre   Cabo HDMI           2571
               Monitor 27"         2655
               Mouse Gamer         2611
               Notebook Dell       2770
               Notebook HP         2511
               Smartphone Samsung  2603
               Teclado Mecânico    2598
               iPhone 14           2540
Recife         Cabo HDMI           2534
               Monitor 27"         2647
               Mouse Gamer         2639
               Notebook Dell       2566
               Notebook HP         2651
               Smartphone Samsung  2660
               Teclado Mecânico    2775
               iPhone 14           2652
Rio De Janeiro Cabo HDMI           2747
               Monitor 27"         2798
               Mouse Gamer         2652
               Notebook Dell       2534
               Notebook HP         2614
               Smartphone Samsung  2626
               Teclado Mecânico    2548
               iPhone 14           2702
Salvador       Cabo HDMI           2566
               Monitor 27"         2545
               Mouse Gamer         2711
               Notebook Dell       2512
               Notebook HP         2785
               Smartphone Samsung  2627
               Teclado Mecânico    2579
               iPhone 14           2671
São Paulo      Cabo HDMI           2649
               Monitor 27"         2796
               Mouse Gamer         2714
               Notebook Dell       2535
               Notebook HP         2592
               Smartphone Samsung  2476
               Teclado Mecânico    2589
               iPhone 14           2735

                                    Qtd
Produto            Loja
Cabo HDMI          Belo Horizonte  2636
                   Curitiba        2698
                   Online           403
                   Porto Alegre    2571
                   Recife          2534
                   Rio De Janeiro  2747
                   Salvador        2566
                   São Paulo       2649
Monitor 27"        Belo Horizonte  2625
                   Curitiba        2626
                   Online           332
                   Porto Alegre    2655
                   Recife          2647
                   Rio De Janeiro  2798
                   Salvador        2545
                   São Paulo       2796
Mouse Gamer        Belo Horizonte  2465
                   Curitiba        2600
                   Online           379
                   Porto Alegre    2611
                   Recife          2639
                   Rio De Janeiro  2652
                   Salvador        2711
                   São Paulo       2714
Notebook Dell      Belo Horizonte  2654
                   Curitiba        2517
                   Online           369
                   Porto Alegre    2770
                   Recife          2566
                   Rio De Janeiro  2534
                   Salvador        2512
                   São Paulo       2535
Notebook HP        Belo Horizonte  2775
                   Curitiba        2529
                   Online           442
                   Porto Alegre    2511
                   Recife          2651
                   Rio De Janeiro  2614
                   Salvador        2785
                   São Paulo       2592
Smartphone Samsung Belo Horizonte  2597
                   Curitiba        2444
                   Online           311
                   Porto Alegre    2603
                   Recife          2660
                   Rio De Janeiro  2626
                   Salvador        2627
                   São Paulo       2476
Teclado Mecânico   Belo Horizonte  2609
                   Curitiba        2742
                   Online           343
                   Porto Alegre    2598
                   Recife          2775
                   Rio De Janeiro  2548
                   Salvador        2579
                   São Paulo       2589
iPhone 14          Belo Horizonte  2478
                   Curitiba        2652
                   Online           390
                   Porto Alegre    2540
                   Recife          2652
                   Rio De Janeiro  2702
                   Salvador        2671
                   São Paulo       2735

In [84]:
display(df_vendasv2.head())

#quais gerentes bateram a meta em janeiro de 2023--------------
df_meta = df_vendasv2[(df_vendasv2["Data"].dt.year == 2023) & (df_vendasv2["Data"].dt.month == 1)]

df_meta = df_meta[["Loja", "Faturamento"]].groupby("Loja", as_index=False).sum()  #agrupamento por loja e somando o faturamento

#juntando duas bases de dados
#df_meta = pd.concat([tabela1, tabela2]) necessario ter colunas identicas, juntar uma na outra, so linhas diferentes

#existe tb how=""left, inner, outer, join, inner join, left join
df_meta = df_meta.merge(df_gerentes, on="Loja", how="left") # tem o mesmo nome de coluna em ambas tabelas, posso usar o on, se for nome diferente usar left on, right on
df_meta["Bateu Meta"] = np.where(df_meta["Faturamento"] >= df_meta["Meta_Mensal"], "Sim", "Nao")
display(df_meta)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Venda,Regiao
0,1700,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_14435,40.0,Presencial,Sul
1,12848,2023-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_4327,40.0,Presencial,Sudeste
2,35599,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_18680,40.0,Presencial,Sul
3,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,40.0,Presencial,Sul
4,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,40.0,Presencial,Sul

             Loja  Faturamento   Gerente  Meta_Mensal Bateu Meta
0  Belo Horizonte    1779100.0   Juliana      55000.0        Sim
1        Curitiba    1986920.0   Roberto      45000.0        Sim
2          Online     404570.0       NaN          NaN        Nao
3    Porto Alegre    1726640.0     Pedro      42000.0        Sim
4          Recife    1779020.0    Marcos      48000.0        Sim
5  Rio De Janeiro    1736830.0  Fernanda      60000.0        Sim
6        Salvador    1686070.0       Ana      52000.0        Sim
7       São Paulo    1831140.0    Carlos      50000.0        Sim

In [89]:
#faturamento por mes/ano
df_vendasv2["Mes-Ano"] = df_vendasv2["Data"].dt.to_period("M") #criando a coluna mes ano e nela sendo apenas o mes da coluna data
df_vendas_mes = df_vendasv2[["Mes-Ano", "Faturamento"]].groupby("Mes-Ano").sum()
#df_vendas_mes.plot() plotly
df_vendas_mes["Faturamento"] = df_vendas_mes["Faturamento"].map("R${:,.2f}".format) ##formatando para real
df_vendas_mes = df_vendas_mes.sort_values(by="Faturamento", ascending=False) #ordenando do maior para o menor
display(df_vendas_mes)

             Faturamento
Mes-Ano
2023-08  R$12,989,130.00
2024-10  R$12,942,070.00
2023-05  R$12,940,470.00
2023-01  R$12,930,290.00
2023-10  R$12,918,990.00
2024-05  R$12,831,810.00
2024-08  R$12,764,560.00
2024-01  R$12,741,000.00
2024-03  R$12,711,500.00
2024-07  R$12,711,490.00
2023-07  R$12,550,990.00
2023-04  R$12,528,900.00
2024-12  R$12,522,410.00
2023-03  R$12,516,080.00
2023-12  R$12,488,190.00
2024-04  R$12,461,860.00
2023-06  R$12,455,820.00
2024-06  R$12,356,650.00
2023-09  R$12,118,180.00
2024-09  R$12,001,410.00
2024-11  R$11,924,910.00
2023-11  R$11,883,670.00
2024-02  R$11,666,800.00
2023-02  R$11,515,150.00